---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos_8
    image: bambrino/centos:8
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - lint
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
