---
- name: Download vector rpm
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/\
          vector-{{ vector_version }}-1.{{ vector_arch }}.rpm"
    dest: "/tmp/vector-{{ vector_version }}.rpm"
    mode: '0644'

- name: Install vector rpm
  ansible.builtin.package:
    name:
      - /tmp/vector-{{ vector_version }}.rpm
    disable_gpg_check: true
